# Generated by Django 3.0.2 on 2020-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('image', models.FileField(blank=True, upload_to='images/accounts/')),
                ('follows', models.ManyToManyField(blank=True, related_name='_account_follows_+', to='accounts.Account')),
            ],
        ),
    ]
